apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-webserver-appset
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
    path: appset
    repoURL: https://github.com/IonOlaruAnant/preview-environments-example.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
