replicaCount: 1
name: trivial-go-web-app
env: staging
namespace: staging
image:
  name: webserver-simple
  tag: '189b18ebc5569f3e17e31197ea7d3cfb7db551ef'
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  port: 8418
  targetPort: 8080
  portName: http
