replicaCount: 1
name: go-webserver
# env: apps-staging
namespace: apps-preview
container:
  name: go-webserver
image:
  name: "iondockeranant/go-webserver"
  tag: "0.0.1"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8418
  targetPort: 8080
  portName: http
